import 'package:json_annotation/json_annotation.dart';

part 'book.g.dart'; // This file is generated by json_serializable

@JsonSerializable()
class Book {
  final MultilingualText book;
  final MultilingualText theme;
  final MultilingualText introduction;
  final List<Chapter> chapters;

  Book(
      {required this.book,
      required this.theme,
      required this.introduction,
      required this.chapters});

  // Factory method to create a Book instance from a map
  factory Book.fromJson(Map<String, dynamic> json) => _$BookFromJson(json);

  // Method to convert Book instance into a map
  Map<String, dynamic> toJson() => _$BookToJson(this);
}

@JsonSerializable()
class Chapter {
  @JsonKey(ignore: true) // This will not be serialized/deserialized
  int get id => number;
  final int number;
  final MultilingualText introduction;
  final List<Verse> verses;

  Chapter(
      {required this.number, required this.introduction, required this.verses});

  factory Chapter.fromJson(Map<String, dynamic> json) =>
      _$ChapterFromJson(json);
  Map<String, dynamic> toJson() => _$ChapterToJson(this);
}

@JsonSerializable()
class Verse {
  @JsonKey(ignore: true) // This will not be serialized/deserialized
  String get id => key;
  final String key;
  final MultilingualText text;

  Verse({required this.key, required this.text});

  factory Verse.fromJson(Map<String, dynamic> json) => _$VerseFromJson(json);
  Map<String, dynamic> toJson() => _$VerseToJson(this);
}

@JsonSerializable()
class MultilingualText {
  final String en;
  final String zh;

  MultilingualText({required this.en, required this.zh});

  factory MultilingualText.fromJson(Map<String, dynamic> json) =>
      _$MultilingualTextFromJson(json);
  Map<String, dynamic> toJson() => _$MultilingualTextToJson(this);
}

class AnimeBook {
  final String id;
  final String engTitle;
  final String zhoTitle;
  final String period;
  final String imageName;

  AnimeBook(
      {required this.id,
      required this.engTitle,
      required this.zhoTitle,
      required this.period,
      required this.imageName});
}
